sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t bolian/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true bolian/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-us-east-1-757730469761"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

